openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /magic:
    post:
      tags:
        - answer-controller
      operationId: addAnswer
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        '201':
          description: Created
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Answer'
  /word:
    get:
      tags:
        - word-controller
      operationId: getWord
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /quote:
    get:
      tags:
        - quote-controller
      operationId: getQuoteList
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    Answer:
      type: object
      properties:
        id:
          type: integer
          format: int32
        question:
          type: string
        answer:
          type: string
